#!/usr/bin/env python3
"""Extract the Fluid Engine mobile/desktop grid placements from the archived pages.
Squarespace emits two independent CSS Grids per section: a base (mobile, <768px)
and a @media (min-width:768px) override. Every block gets a grid-area in each."""
import re, os, json, glob, sys

REF = os.path.join(os.path.dirname(__file__), '..', '..', '_reference', 'squarespace', 'extracted')

def split_media(css):
    base, desk, i = [], [], 0
    while True:
        m = re.search(r'@media \(min-width: 768px\) \{', css[i:])
        if not m:
            base.append(css[i:]); break
        st, ob = i + m.start(), i + m.end()
        base.append(css[i:st])
        depth, j = 1, ob
        while j < len(css) and depth:
            depth += (css[j] == '{') - (css[j] == '}'); j += 1
        desk.append(css[ob:j-1]); i = j
    return "".join(base), "".join(desk)

def rules(css):
    """block -> {grid-area, justify, align} for .fe-block-* rules."""
    out = {}
    for m in re.finditer(r'\.(fe-block-[\w-]+)\s*\{([^{}]*(?:\{[^{}]*\}[^{}]*)*)\}', css):
        name, body = m.group(1), m.group(2)
        a = re.search(r'grid-area:\s*([^;]+);', body)
        if a: out.setdefault(name, {})['area'] = a.group(1).strip()
    for m in re.finditer(r'\.(fe-block-[\w-]+)\s+\.sqs-block\s*\{([^{}]*)\}', css):
        j = re.search(r'justify-content:\s*([^;]+);', m.group(2))
        if j: out.setdefault(m.group(1), {})['justify'] = j.group(1).strip()
    return out

def grid_def(css):
    g = {}
    m = re.search(r'grid-template-columns:\s*([^;]+);', css)
    if m: g['cols'] = re.sub(r'\s+', ' ', m.group(1)).strip()
    m = re.search(r'grid-template-rows:\s*repeat\((\d+)', css)
    if m: g['rows'] = int(m.group(1))
    for k, p in (('rowGap', 'row-gap'), ('colGap', 'column-gap')):
        m = re.search(p + r':\s*([^;]+);', css)
        if m: g[k] = m.group(1).strip()
    return g

report, data = [], {}
for path in sorted(glob.glob(os.path.join(REF, '*.inline.css'))):
    page = os.path.basename(path).replace('.inline.css', '')
    css = open(path, encoding='utf-8').read()
    b, d = split_media(css)
    B, D = rules(b), rules(d)
    data[page] = {'mobile': B, 'desktop': D, 'mobileGrid': grid_def(b), 'desktopGrid': grid_def(d)}
    blocks = [k for k in B if 'area' in B[k]]
    if not blocks: 
        report.append(f"\n## {page}\n\nClassic (non-Fluid-Engine) sections — ordinary responsive reflow, no grid table.\n")
        continue
    report.append(f"\n## {page}\n")
    report.append(f"Mobile grid: {grid_def(b).get('rows','?')} rows, gaps {grid_def(b).get('rowGap','?')}/{grid_def(b).get('colGap','?')}  ")
    report.append(f"Desktop grid: {grid_def(d).get('rows','?')} rows\n")
    report.append("| block | mobile `grid-area` | desktop `grid-area` | moved |")
    report.append("|---|---|---|---|")
    def key(k):
        a = B[k]['area'].split('/')
        try: return int(a[0])
        except: return 0
    for k in sorted(blocks, key=key):
        mb = B[k].get('area', '—'); dk = D.get(k, {}).get('area', '—')
        report.append(f"| `{k[9:]}` | `{mb}` | `{dk}` | {'yes' if mb != dk else 'no'} |")

out = os.path.join(os.path.dirname(__file__), '..')
open(os.path.join(out, 'GRID.md'), 'w').write(
    "# Fluid Engine grid placements\n\n"
    "Auto-generated by `tools/extract-grid.py` from the archived Squarespace pages.\n"
    "`grid-area` is `row-start / col-start / row-end / col-end`.\n"
    "Mobile grid is 8 columns, desktop 24 — so column numbers are **not** comparable across the two.\n"
    + "\n".join(report) + "\n")
json.dump(data, open(os.path.join(out, 'tokens', 'grid.json'), 'w'), indent=2)
print("wrote _design/GRID.md and _design/tokens/grid.json")
